welcome: "Welcome to delivery system."
enter-text: "Please enter valid line of package data, then hit enter button. You can continue by entering next line of package data. If you want to quit the app, just write 'quit' and again hit enter button."
line-format-instructions: "Valid format: <weight: positive number, max weight: 10kg, maximal 3 decimal places, . (dot) as decimal separator><space><postal code: fixed 5 digits>"
line-example: "example: '3.4 08801'"
quit-app-text: "Delivery system is quiting, have a nice day."
invalid-line-text: "Entered line is invalid, please enter again valid line."
output-from-storage: "Currently, these deliveries are stored :"
rules-line-pattern: "^(([0-9][.][0-9]{1,3})|([0-9]|(10))) [0-9]{5}$"
quit-app-command: "quit"
ask-for-price-list: "Do you want load a weight price list? 'Y' for loading, anything else for not loading, push enter button and you can continue to entering lines of data"
enter-price-list-name: "Enter path of file and '\\' + file name, where are fees saved, example:'D:\\external data\\priceList'"